# Generated by Django 2.0.2 on 2018-02-15 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('Authors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pp', models.ImageField(blank='true', upload_to='profile_image')),
                ('read', models.ManyToManyField(related_name='user_book_read', to='books.Book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_author_follow', models.ManyToManyField(to='Authors.Author')),
                ('user_book_rate', models.ManyToManyField(through='Users.BookRate', to='books.Book')),
                ('user_category_fav', models.ManyToManyField(to='books.Category')),
                ('wishlist', models.ManyToManyField(related_name='user_book_wishlist', to='books.Book')),
            ],
        ),
        migrations.AddField(
            model_name='bookrate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.UserProfile'),
        ),
    ]
