# Generated by Django 2.0.2 on 2018-02-14 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authors', '0001_initial'),
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='read',
            field=models.ManyToManyField(related_name='user_book_read', to='books.Book'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_author_follow',
            field=models.ManyToManyField(to='Authors.Author'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_category_fav',
            field=models.ManyToManyField(to='books.Category'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wishlist',
            field=models.ManyToManyField(related_name='user_book_wishlist', to='books.Book'),
        ),
    ]
