# Generated by Django 2.0.2 on 2018-02-15 04:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180214_0048'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0002_auto_20180215_0357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReadedList',
            new_name='readList',
        ),
    ]
