# Generated by Django 2.0.2 on 2018-03-03 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180214_0048'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0004_followlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='rateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_val', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='rate',
            name='book',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='user',
        ),
        migrations.DeleteModel(
            name='rate',
        ),
    ]
