# Generated by Django 2.0.2 on 2018-03-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='book',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ratelist',
            name='rate_val',
        ),
        migrations.AddField(
            model_name='ratelist',
            name='rate',
            field=models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=1),
        ),
        migrations.DeleteModel(
            name='rate',
        ),
    ]
