# Generated by Django 2.0.2 on 2018-02-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50)),
                ('author_bio', models.CharField(max_length=1000)),
                ('author_pp', models.CharField(max_length=1000)),
            ],
        ),
    ]
