# Generated by Django 2.0.2 on 2018-02-14 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='Author_Books',
        ),
    ]
