# Generated by Django 2.0.2 on 2018-03-10 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authors', '0002_authors'),
        ('Users', '0003_auto_20180310_0218'),
        ('books', '0002_auto_20180310_0218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
