# Generated by Django 2.0.2 on 2018-03-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authors', '0002_remove_authors_author_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='author_img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
