# Generated by Django 2.0.2 on 2018-02-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180210_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50)),
                ('author_bio', models.CharField(max_length=1000)),
                ('author_pp', models.CharField(max_length=1000)),
            ],
        ),
    ]
