# Generated by Django 2.0.2 on 2018-02-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
