# Generated by Django 2.0 on 2018-02-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
