# Generated by Django 2.0.2 on 2018-02-14 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Author',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='book',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='read',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_author_follow',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_book_rate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_category_fav',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wishlist',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
