# Generated by Django 2.0.2 on 2018-02-12 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.ManyToManyField(related_name='user_book_read', to='books.Book')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='read',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_author_follow',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_book_rate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_category_fav',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wishlist',
        ),
        migrations.AlterField(
            model_name='rate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.UserProfile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_author_follow',
            field=models.ManyToManyField(to='books.Author'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_book_rate',
            field=models.ManyToManyField(through='books.Rate', to='books.Book'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_category_fav',
            field=models.ManyToManyField(to='books.Category'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wishlist',
            field=models.ManyToManyField(related_name='user_book_wishlist', to='books.Book'),
        ),
    ]
