# Generated by Django 2.0.2 on 2018-03-10 02:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Authors', '0002_authors'),
        ('Users', '0003_auto_20180310_0218'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100)),
                ('book_description', models.TextField()),
                ('published_at', models.DateField()),
                ('book_cover', models.FileField(blank=True, null=True, upload_to='')),
                ('Author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authors.Authors')),
                ('book_category', models.ManyToManyField(to='books.BookCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Visitor', max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='books.Books')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='Author',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='book',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='user',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
