# Generated by Django 2.0.2 on 2018-02-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Book_cover',
            new_name='book_cover',
        ),
    ]
