# Generated by Django 2.0.2 on 2018-02-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180212_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_pp',
            field=models.ImageField(blank='true', upload_to='profile_image'),
        ),
    ]
