# Generated by Django 2.0.2 on 2018-02-14 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authors', '0002_remove_authors_author_books'),
        ('books', '0002_auto_20180214_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='categories',
            new_name='book_category',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='image',
            new_name='book_cover',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='summary',
            new_name='book_description',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='country',
            new_name='book_title',
        ),
        migrations.RemoveField(
            model_name='books',
            name='author',
        ),
        migrations.RemoveField(
            model_name='books',
            name='link',
        ),
        migrations.RemoveField(
            model_name='books',
            name='title',
        ),
        migrations.AddField(
            model_name='books',
            name='Author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authors.Authors'),
        ),
    ]
