# Generated by Django 2.0.2 on 2018-03-03 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
