# Generated by Django 2.0.2 on 2018-03-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20180317_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='Visitor', max_length=200),
        ),
    ]
